@startuml register-with-orchestrator

title
 Registering a Pod with an Orchestrator
end title

autonumber "<b>(R0)"
actor maintainer as M
participant Dashboard as D
participant orchestrator.kb.nl as O
participant pod.kb.nl as Pod
participant netwerkdigitaalerfgoed.nl as NDE

autonumber stop
M -[#0000FF]> D: Connect to\na new orchestrator for pod.kb.nl

== Discover inbox & create a new orchestrator ==

autonumber resume
D --> O : HEAD /
D <-- O: 200 OK\nLink: <orchestrator.kb.nl/inbox>;\nrel="http://www.w3.org/ns/ldp#inbox"

D -> O : POST /inbox\n{ LDN Create orchestrator\nfor pod.kb.nl }
D <-- O : 201 Created\nLocation: orchestrator.kb.nl/inbox/1

autonumber stop
O -[#0000FF]> O: Create index entry\nfor pod.kb.nl

autonumber resume
O --> Pod : HEAD /
O <-- Pod: 200 OK\nLink: <pod.kb.nl/inbox>;\nrel="http://www.w3.org/ns/ldp#inbox"

O --> Pod : POST /inbox\n{ LDN Created orchestrator for pod.kb.nl at /pod.kb.nl }
O <-- Pod : 201 Created\nLocation: pod.kb.nl/inbox/1

autonumber stop
D -[#0000FF]> M: Tell user orchestrator.kb.nl/pod-kb-nl\nis up and running

== Add policies to orchestrator ==

M -[#0000FF]> D: Add the KB policy and the NDE policy

autonumber resume
D --> O : HEAD /pod-kb-nl
D <-- O: 200 OK\nLink: <orchestrator.kb.nl/pod-kb-nl/inbox>;\nrel="http://www.w3.org/ns/ldp#inbox"

D -> O : POST /pod-kb-nl/inbox\n{ LDN Add pod.kb.nl/policy.ttl }
D <-- O : 201 Created\nLocation: orchestrator.kb.nl/pod-kb-nl/inbox/1

O -> Pod: GET /policy.ttl
O <-- Pod: 200 OK

autonumber stop
O -[#0000FF]> O: Index pod.kb.nl/policy.ttl

autonumber resume
D -> O : POST /pod.kb.nl/inbox\n{ LDN Add netwerkdigitaalerfgoed.nl/policy.ttl }
D <-- O : 201 Created\nLocation: orchestrator.kb.nl/pod-kb-nl/inbox/2

O -> NDE: GET /policy.ttl
O <-- NDE: 200 OK

autonumber stop
O -[#0000FF]> O: Index netwerkdigitaalerfgoed.nl/policy.ttl

D -[#0000FF]> M: Tell user orchestrator.kb.nl/pod.kb.nl\nhas been configured with both policies 

@enduml